# Generated by Django 4.2.27 on 2026-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0006_remove_studentprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
    ]
