# Generated by Django 4.2.27 on 2026-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0007_studentprofile_profile_pic_studentprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
