# Generated by Django 4.2.27 on 2026-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0008_studentprofile_approval_status_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approval_requested',
            field=models.BooleanField(default=False),
        ),
    ]
