# Generated by Django 4.2.27 on 2026-03-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0009_studentprofile_approval_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_publication',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('faculty', 'faculty'), ('organization', 'organization')], default='', max_length=20),
        ),
    ]
