# Generated by Django 5.1.1 on 2026-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0012_talvynconversation_talvynmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='ai_suggestions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ai_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
